version: '2.4'

services:
  app:
    container_name: openhab
    image: openhab/openhab:3.0.1
    restart: unless-stopped
    # Pour faire fonctionner le UpNP discovery, si décommenté alors les ports sont à supprimer
    # network_mode: host
    ports:
     - 8080:8080
     - 8443:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DIRECTORY}/addons:/openhab/addons
      - ${DIRECTORY}/conf:/openhab/conf
      - ${DIRECTORY}/userdata:/openhab/userdata
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Paris"
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0

 